name: 'Pterodactyl SFTP Deploy'
author: 'DEPSTRCZ'
description: 'Github action that allows you to deploy youR project to your Pterodactyl server via SFTP'
branding:
  color: blue
  icon: upload-cloud
inputs:
  host:
    description: 'FTP host address Example:  192.168.1.40 or sftp.your-host.com'
    required: true
  port:
    description: 'FTP port'
    required: false
    default: 21
  username:
    required: true
    description: 'Ftp username'
  password:
    required: true
    description: 'Ftp password'
  panel_domain:
    required: true
    description: 'Pterodactyl panel domain'
  api_key:
    required: true
    description: 'Pterodactyl api key'
  server_id:
    required: true
    description: 'Pterodactyl server id'
  remote_folder:
    required: false
    default: ./
    description: 'The remote folder location of your FTP server'
  local_folder:
    required: false
    default: dist
    description: 'The local folder to upload from'
  delete_remote:
    required: false
    default: false
    description: 'Delete all files in remote folder'
  include:
    required: false
    default: '["*", "**/*"]'
    description: 'includes'
  exclude:
    required: 
    default: '[]'
    description: 'exclude'
  passive:
    required: false
    default: false
    description: 'passive'
runs:
  using: 'node16'
  main: 'dist/index.js'
